### PR TITLE
Dark mode added

### PR DESCRIPTION
**Pull request by omidnikrah**
Dark mode toggle added to settings 🚀

### CODE REVIEW

**Comment by dantehemerson** [comment]
Looks good :+1:

**Comment by anguianomaria** [comment]
Hola  yo ni entiendo esto de que se trata

**Comment by ttuygun** [comment]
@buunguyen can we merge this request?

**Comment by buunguyen** [comment]
Thanks for this PR. Unfortunately, I cannot merge because:

* The code in this PR isn't consistent with existing code. This could be updated but the bigger thing is: 
* I'm thinking of building theming support of Octotree. And it would also control GitHub itself, not just the tree.

**Pull request closed without merging**
