### PR TITLE
truncate filename if it is overflow

### PR DESCRIPTION
**Pull request by nphi**
Screen Shot 2019-08-17 at 6 24 47 PM

### CODE REVIEW

**Comment by buunguyen** [comment]
Nice. But the first line: the directory name looks funny, why so many "..."s?

**Comment by nphi** [comment]
> Nice. But the first line: the directory name looks funny, why so many "..."s?

**Comment by buunguyen** [comment]
@nphi I think you can address that by updating the CSS selector so that it applies to the last sibling within a parent.

**Comment by nphi** [comment]
a @buunguyen, it wouldn't work if other siblings contain long text. Truncating the last sibling is not enough.

**Pull request merged**
