### PR TITLE
fix New PR page layout

### PR DESCRIPTION
**Pull request by endyquang**
### Screenshots
Before
image

After
Peek 2020-02-23 14-48

### CODE REVIEW

**Comment by buunguyen** [comment]
@endyquang does this also address these issues? https://github.com/ovity/octotree/issues/902

**Comment by endyquang** [comment]
@buunguyen No this doesn't. This will only fix the PR page

**Comment by buunguyen** [comment]
Can you check the linked issue too, see if can change to fix it so that we only regression once?

**Comment by endyquang** [comment]
Certainly this PR should fix every possible pages. I had checked the 902 and could not find any quick solution, i'll try some more

**Comment by buunguyen** [comment]
In the GIF, why did the margin changed when switching from .gitignore to gulpfile.js? Also when switching from the diff page to code page, margin also changes.

**Comment by endyquang** [comment]
@buunguyen it's because of the scrollbar of the browser. The scrollbar pop out for gulpfile and dissapear when open .gitignore.
I suppose a Mac does't have this, but this is a normal behavior with linux and windows

**Pull request merged**
